runtime: python27
api_version: 1
threadsafe: true
instance_class: F2

inbound_services:
- mail

handlers:
- url: /_ah/mail/.+
  script: recv_email_update_sheet.app
  login: admin
#- url: /authorize
#  script: auth.app
- url: /updatesheet
  script: recv_email_update_sheet.app
#- url: /auth2
#  script: auth2_test.app
#- url: /oauth2callback
#  script: auth.app